### ISSUE TITLE
Cannot create a new Python notebook

### ISSUE THREAD

**Issue by CarlosYeverino** [caffe2/tutorials#6]
When I try to create a new Python 2 notebook (only available option for me), I get the following error in jupyter:
Creating Notebook Failed
An error occurred while creating a new notebook.
Unexpected error while running post hook save: [Error 2] The system cannot find the file specified

My configuration:
Python 2.7
I installed jupyter using pip.

Below the console output
[I 00:17:13.266 NotebookApp] Serving notebooks from local directory: D:\Yeverino\git_projects\caffe2_tutorials
[I 00:17:13.266 NotebookApp] 0 active kernels
[I 00:17:13.266 NotebookApp] The Jupyter Notebook is running at:
[I 00:17:13.269 NotebookApp] http://localhost:8888/?token=4221257bd26d14d480e4347bb53396e07ded1f09026fcff9
[I 00:17:13.269 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 00:17:13.270 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=4221257bd26d14d480e4347bb53396e07ded1f09026fcff9&token=4221257bd26d14d480e4347bb53396e07ded1f09026fcff9
[I 00:17:13.394 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[I 00:17:17.466 NotebookApp] Creating new notebook in
[NbConvertApp] Converting notebook Untitled5.ipynb to script
[NbConvertApp] Writing 0 bytes to Untitled5.txt
[E 00:17:18.387 NotebookApp] Post-save hook failed o-n D:\Yeverino\git_projects\caffe2_tutorials\Untitled5.ipynb
    Traceback (most recent call last):
      File "c:\python27\lib\site-packages\notebook\services\contents\filemanager.py", line 135, in run_post_save_hook
        self.post_save_hook(os_path=os_path, model=model, contents_manager=self)
      File "D:\Yeverino\git_projects\caffe2_tutorials\jupyter_notebook_config.py", line 26, in post_save
        os.rename(full_py_name, new_py_location)
    WindowsError: [Error 2] The system cannot find the file specified
[W 00:17:18.390 NotebookApp] 500 POST /api/contents (::1): Unexpected error while running post hook save: [Error 2] The system cannot find the file specified
[W 00:17:18.390 NotebookApp] Unexpected error while running post hook save: [Error 2] The system cannot find the file specified
[E 00:17:18.391 NotebookApp] {
      "Origin": "http://localhost:8888",
      "Content-Length": "19",
      "Accept-Language": "es-ES,es;q=0.9,de;q=0.8,en;q=0.7",
      "Accept-Encoding": "gzip, deflate, br",
      "X-Xsrftoken": "2|f594acfd|b21763f337c6c61245f37d965d8f867f|1531174011",
      "Host": "localhost:8888",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36",
      "Connection": "keep-alive",
      "X-Requested-With": "XMLHttpRequest",
      "Referer": "http://localhost:8888/tree",
      "Cookie": "_xsrf=2|f594acfd|b21763f337c6c61245f37d965d8f867f|1531174011; username-localhost-8888=\"2|1:0|10:1531174633|23:username-localhost-8888|44:MDY1Zjg5MmM1MGNiNGQwY2E2ZDZmOWJkM2Q1Yjg4OTM=|b208a39bfadbe492e0449edddeeadfc783f9b3aaa0d96e9f3de93429a2757c3d\"",
      "Content-Type": "application/json"
    }
[E 00:17:18.391 NotebookApp] 500 POST /api/contents (::1) 926.00ms referer=http://localhost:8888/tree

**Comment by orionr** [comment]
@CarlosYeverino - apologies that we were slow on responding here. Did you solve your issue?
