### ISSUE TITLE
No handlers - MINST tutorial error - maybe related to lmdb

### ISSUE THREAD

**Issue by CarlosYeverino** [caffe2/tutorials#7]
**It seems that reported error is related to lmdb. I compiled pythorch setting -DUSE_LMDB=ON in build_windows.bat, however the compiler did not recognize it and console output showed USE_LMDB=OFF during compilation. How can I fix the issue below?**

Console Output:
No handlers could be found for logger "caffe2.python.workspace"

Traceback (most recent call last):
  File "D:\Yeverino\Python_scripts\minst_caffe2_tutorial\1.py", line 254, in <module>
    workspace.RunNetOnce(train_model.param_init_net)
  File "D:\Yeverino\git_projects\pytorch\build\caffe2\python\workspace.py", line 199, in RunNetOnce
    StringifyProto(net),
  File "D:\Yeverino\git_projects\pytorch\build\caffe2\python\workspace.py", line 178, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at db.h:190] db_. Cannot open db: C:\Users\Carlos\caffe2_notebooks\tutorial_data\mnist\mnist-train-nchw-lmdb of type lmdb Error from operator: 
output: "dbreader_C:\\Users\\Carlos\\caffe2_notebooks\\tutorial_data\\mnist\\mnist-train-nchw-lmdb" name: "" type: "CreateDB" arg { name: "db_type" s: "lmdb" } arg { name: "db" s: "C:\\Users\\Carlos\\caffe2_notebooks\\tutorial_data\\mnist\\mnist-train-nchw-lmdb" }

**Comment by CarlosYeverino** [comment]
Related issue stated in https://github.com/pytorch/pytorch/issues/9736
